services:
  moondream-api:
    build: .
    image: moondream-api:latest
    container_name: moondream_api
    restart: unless-stopped
    environment:
      - MODEL_NAME=moondream-0_5b-int8 # also moondream-2b-int8 available
      - MOONDREAM_500M_URL=https://huggingface.co/vikhyatk/moondream2/resolve/9dddae84d54db4ac56fe37817aeaeb502ed083e2/moondream-0_5b-int8.mf.gz?download=true
      - MOONDREAM_2B_URL=https://huggingface.co/vikhyatk/moondream2/resolve/9dddae84d54db4ac56fe37817aeaeb502ed083e2/moondream-2b-int8.mf.gz?download=true
    ports:
      - 18000:8000
    volumes:
      - ./model_cache:/app/model_cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s