[project]
name = "moondream-api"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.7",
    "moondream>=0.0.6",
    "psutil>=6.1.1",
    "pybind11>=2.13.6",
    "tiktoken>=0.8.0",
]
